server:
  port: 8083

egc:
  base:
    ackey: 1d0ec00844530316a
  jpush:
    appKey: ef97eeebd2f3459bca85ee02a
    masterSecret: 667f038e269bd1111aa1183fa
  sms:
    accessKeyId: LTAIbW4uz7fAtIZBa
    accessKeySecret: JiQERgLeEkUeWg1WsIIGXYFKpVoEM3a


